resources:
  - name: JohnCabGitRepo
    type: GitRepo
    configuration:
      gitProvider: john_cab_github
      path: john-cab/jfrog-pipelines-simple-example
      branches:
        include: master
pipelines:
  - name: john_cab_app_pipeline  
    configuration:
      environmentVariables:
        readOnly:
           MY_MESSAGE: '"Hello-World"'
    steps:
      - name: step-1
        type: Bash
        InputResources:
          - name: JohnCabGitRepo
        execution:
          onExecute:
            - echo "Hello Wolrd 1"
