resources:
  - name: JohnCabGitRepo
    type: GitRepo
    configuration:
      gitProvider: john_cab_github
      path: john-cab/jfrog-pipelines-simple-example2
      branches:
        include: master
pipelines:
  - name: john_cab_app_pipeline_newexample  
    configuration:
      environmentVariables:
        readOnly:
           MY_MESSAGE: '"Hello-World"'
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: JohnCabGitRepo
        execution:
          onStart:
            - echo "Hello Wolrd 1"
          onComplete:
            - echo "Goodbye World 1"
